---
title: "Client Report - Exploring Names"
subtitle: "Unit 1 Task 1"
author: "Rayce O'Rullian"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("names_year_csv.csv")
```
## QUESTION 1

__What was the earliest year that the name ‘Felisha’ was used?__

The earliest recorded year that "Felisha" appeared was in 1964.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q1

df.filter(pl.col("name") == "Felisha").select("year").min()
```


## QUESTION 2

__What year had the most babies named 'David'? How many babies were named 'David' that year?__

The most babies that were named "David" in one year 86389, and that was in 1955.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q2

df.filter(pl.col("name") == "David").sort("Total", descending=True).head(1)
```


## QUESTION 3

__What year did your name hit its peak? How many babies were named your name in that year?__

In 2012, there were 24 babies named Rayce.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q3
df.filter(pl.col("name") == "Rayce").sort("Total", descending=True).head(1)
```


## QUESTION 4

__In the most recent year, what was the most common female name in Utah?__ 

The most common female name in Utah, in the latest recorded year (2024), was Olivia, with 14718 results.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q5
df.filter(pl.col("year") == pl.col("year").max()).sort("UT", descending=True).head(10)

```


---
