---
title: "Client Report - Flights: Column Aggregation"
subtitle: "Unit 2 Task 2"
author: "Rayce O'Rullian"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```


## QUESTION 1

__Calculate the sample size (i.e. number of rows in the dataset) for each airport in each year__. What do you notice?

_I used the "len()" method to count how many rows there are for each airport, and the most common result is 12. I'm not sure why this is, but I'll guess that it has to do with the 12 months of the year, although that doesn't explain why there's an 11 and a 23._

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Include and execute your code here
thing = df.group_by(["airport_code", "year"]).len()

thing

```

## QUESTION 2

__Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours. 

_I know my table might not provide the most conclusive results, but I've shown each airport's number of flights and number of delays, and found the difference between them. I interpreted that the greater difference between total flights and total delays, the better. If the number of flights and the number of delays are closer together (meaning they have a smaller difference), then that's bad. Judging by that metric, the airport with the code "IAD" has the worst delays. Of its near-3000 flights, 656 of them were delayed._

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Include and execute your code here
stuff = df.group_by("airport_code", "num_of_delays_total").agg(
    pl.col("num_of_flights_total").sum()
).with_columns(
  (pl.col("num_of_flights_total") - pl.col("num_of_delays_total")).alias("proportion")
).sort("proportion", descending=False)

stuff
# Yes, I know there's no average delay time in hours on my table. I genuinely couldn't figure that one out.
```

## QUESTION 3

__Create a barplot showing the proportion of all flights that are delayed at each airport. Describe what you learn from this graph.__  

_I'll be honest, I really tried to make a bar plot, and I have no idea how to interpret this visual. I'm sorry._

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Include and execute your code here
the_plot = ggplot(stuff, aes(x="airport_code", y="proportion")) + geom_bar()

the_plot

```