---
title: "Client Report - Famous Names"
subtitle: "Unit 1 Task 3"
author: "Rayce O'Rullian"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("names_year_csv.csv")
```



## QUESTION 1

<!-- Make sure at least one of your charts includes reference marks!! -->

__Make a new column that represents the total number of babies with your name for only those states in which you have lived. (If you have only ever lived in one state, pick at least one other state so you get practice summing across columns). Make a graph displaying that total for your name over time.__

_My name has had almost no usage in Idaho and Utah. Both in 2004 and in 2010, there were five babies with my name. That's it. (I was born in 2001 and that's not showing. How dare this graph exclude me?)_

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q1
rayce = (
    df.filter(pl.col("name") == "Rayce")
      .with_columns(
          pl.when(pl.col("Total") > 0)
            .then(pl.col("ID") + pl.col("UT"))
            .alias("my_states")
      )
)

ggplot(rayce, aes(x="year", y="my_states")) + geom_line() + scale_x_continuous(format = "d")

```


## QUESTION 2

1. __Let's look at a name that is special for members of the church: Brigham. For each year, calculate what proportion of babies named Brigham were born in Idaho and Utah? Make a graph displaying the proportion over time.__  

_From 1971 to 1987, all of the Brighams were born in Utah and Idaho. In 1992, none of them were. Then it went back up to 100% for a few years. After 1996, that's when the proportion of Brighams born in Idaho and Utah compared to the rest of the states started fluctuating._

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q2
brigham = (df.filter(pl.col("name") == "Brigham").with_columns(
  pl.when(pl.col("Total") > 0).then((pl.col("ID") +
  pl.col("UT")) / pl.col("Total")).otherwise(None).alias("Idaho_and_Utah")))

ggplot(brigham, aes(x="year", y="Idaho_and_Utah")) + geom_line() + scale_x_continuous(format = "d")

```

<!-- Make sure at least one of your charts includes reference marks!! -->

## QUESTION 3

1. __Consider doing some data validation. For the name David, calculate a sum of all 50 states and District of Columbia for each year. Now compare that total to the value in the 'Total' column. In which years, if any, do they not agree?__

_I couldn't find any years where they don't agree. I have the Total column, and I have a state sum column, and every number for both of those match up._

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q3

david = df.filter(pl.col("name") == "David").with_columns(
    pl.sum_horizontal(pl.all().exclude(["name", "year", "Total"])).alias("state_sum")
)

david
```